---
title: "Demande de stage"
author: "Tamsir Ndong"
date: '2024-03-12'
output: pdf_document
editor_options: 
  markdown: 
    wrap: 72
---

                           Lettre de demande de stage

Monsieur Tamsir Ndong Dakar, le 12 mars 2024

1052 / Zac de Kounoune / Rufisque

77 866 25 64 / 77 650 27 49

tamsirndong03gmail.com

Objet : Demande de stage

Monsieur le Directeur Général,

Etudiant en 2e année de formation en filière ISEP, je me permets de vous
transmettre cette correspondance pour solliciter de votre part
l'obtention d'un stage d'immersion de 8 semaines dans la période
Juillet-Septembre, au sein des services dont vous avez la charge.

Je dois vous signaler Monsieur le Directeur que dans le cadre de notre
formation nous devons effectuer obligatoire dans une structure relevant
de la statistique. C'est cela qui motive ma demande. Ce stage me
permettra aussi de produire un rapport dont la note de soutenance est
prise en compte dans l'évaluation finale. Par ailleurs, il sera une
occasion de mettre en pratique l'ensemble des compétences théoriques
acquises à l'école, de mieux comprendre la communication dans
l'entreprise et de m'exercer au travail en groupe dans vos équipes.

Tout en espérant que ma demande sera traitée avec diligence et que votre
réponse sera favorable, je vous prie de bien vouloir accepter. Monsieur
le Directeur Général, l'expression de ma profonde gratitude.

L'intéréssé

Symbole

T.N.
